apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress  
  annotations:    
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:  
  rules:
  - host: dev.cbsrc.org
    http:
      paths:      
      - path: {{ .Values.services.usermanagement.backend.path }}
        backend:
          serviceName: {{ .Values.services.usermanagement.backend.service }}
          servicePort: 80
      - path: {{ .Values.services.volunteerreporting.backend.path }}
        backend:
          serviceName: {{ .Values.services.volunteerreporting.backend.service }}
          servicePort: 80
      - path: {{ .Values.services.admin.backend.path }}
        backend:
          serviceName: {{ .Values.services.admin.backend.service }}
          servicePort: 80
      - path: {{ .Values.services.usermanagement.frontend.path }}
        backend:
          serviceName: {{ .Values.services.usermanagement.frontend.service }}
          servicePort: 80
      - path: {{ .Values.services.volunteerreporting.frontend.path }}
        backend:
          serviceName: {{ .Values.services.volunteerreporting.frontend.service }}
          servicePort: 80
      - path: {{ .Values.services.admin.frontend.path }}
        backend:
          serviceName: {{ .Values.services.admin.frontend.service }}
          servicePort: 80
