sudo: required

# blocklist
branches:
  except:
  - ci

# safelist
branches:
  only:
  - master

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always

services:
  - docker

before_install:
- docker pull redcrossredcrescent/cbs-cake-build:latest

script:
# - ls -al ${PWD}
- docker run --rm --workdir=/workspace --volume ${PWD}:/workspace redcrossredcrescent/cbs-cake-build:latest ./build.sh