---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-db
  namespace: cbs-system
  labels:
    k9s-app: mongo-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-db-service
  namespace: cbs-system
spec:
  selector:
    k8s-app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      name: mongo