version: '3'
networks:
  cbs-network:
services:
  cbs-usermanagement-core:
    image: redcrossredcrescent/cbs-usermanagement-core:latest
    build:
      context: "../../"
      dockerfile: "Source/UserManagement/Core/Dockerfile"
    volumes:
      - "./cbs-usermanagement-resources.json:/CBS/Core/.dolittle/resources.json"
    networks:
      - "cbs-network"

  cbs-usermanagement-web:
    image: redcrossredcrescent/cbs-usermanagement-web:latest
    build:
      context: "../../Source/"
      dockerfile: "UserManagement/Web/Dockerfile"
      args:
        mode: "build-test"
    expose:
      - "80"
    networks:
      - "cbs-network"